// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: driverspb/drivers_messages.proto

package driverspb

import (
	common "github.com/Binit-Dhakal/Saarathi/pkg/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TripOffer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OfferId       string                 `protobuf:"bytes,1,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	TripId        string                 `protobuf:"bytes,2,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	PickUp        *common.Coordinates    `protobuf:"bytes,3,opt,name=pick_up,json=pickUp,proto3" json:"pick_up,omitempty"`
	DropOff       *common.Coordinates    `protobuf:"bytes,4,opt,name=drop_off,json=dropOff,proto3" json:"drop_off,omitempty"`
	Price         int32                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Distance      float64                `protobuf:"fixed64,6,opt,name=distance,proto3" json:"distance,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TripOffer) Reset() {
	*x = TripOffer{}
	mi := &file_driverspb_drivers_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripOffer) ProtoMessage() {}

func (x *TripOffer) ProtoReflect() protoreflect.Message {
	mi := &file_driverspb_drivers_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripOffer.ProtoReflect.Descriptor instead.
func (*TripOffer) Descriptor() ([]byte, []int) {
	return file_driverspb_drivers_messages_proto_rawDescGZIP(), []int{0}
}

func (x *TripOffer) GetOfferId() string {
	if x != nil {
		return x.OfferId
	}
	return ""
}

func (x *TripOffer) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *TripOffer) GetPickUp() *common.Coordinates {
	if x != nil {
		return x.PickUp
	}
	return nil
}

func (x *TripOffer) GetDropOff() *common.Coordinates {
	if x != nil {
		return x.DropOff
	}
	return nil
}

func (x *TripOffer) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TripOffer) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *TripOffer) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

var File_driverspb_drivers_messages_proto protoreflect.FileDescriptor

const file_driverspb_drivers_messages_proto_rawDesc = "" +
	"\n" +
	" driverspb/drivers_messages.proto\x12\x0fdriversstate.v1\x1a\x10common/geo.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x98\x02\n" +
	"\tTripOffer\x12\x19\n" +
	"\boffer_id\x18\x01 \x01(\tR\aofferId\x12\x17\n" +
	"\atrip_id\x18\x02 \x01(\tR\x06tripId\x123\n" +
	"\apick_up\x18\x03 \x01(\v2\x1a.common.geo.v1.CoordinatesR\x06pickUp\x125\n" +
	"\bdrop_off\x18\x04 \x01(\v2\x1a.common.geo.v1.CoordinatesR\adropOff\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x05R\x05price\x12\x1a\n" +
	"\bdistance\x18\x06 \x01(\x01R\bdistance\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAtB>Z<github.com/Binit-Dhakal/Saarathi/pkg/contracts/dto/driverspbb\x06proto3"

var (
	file_driverspb_drivers_messages_proto_rawDescOnce sync.Once
	file_driverspb_drivers_messages_proto_rawDescData []byte
)

func file_driverspb_drivers_messages_proto_rawDescGZIP() []byte {
	file_driverspb_drivers_messages_proto_rawDescOnce.Do(func() {
		file_driverspb_drivers_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_driverspb_drivers_messages_proto_rawDesc), len(file_driverspb_drivers_messages_proto_rawDesc)))
	})
	return file_driverspb_drivers_messages_proto_rawDescData
}

var file_driverspb_drivers_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_driverspb_drivers_messages_proto_goTypes = []any{
	(*TripOffer)(nil),             // 0: driversstate.v1.TripOffer
	(*common.Coordinates)(nil),    // 1: common.geo.v1.Coordinates
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_driverspb_drivers_messages_proto_depIdxs = []int32{
	1, // 0: driversstate.v1.TripOffer.pick_up:type_name -> common.geo.v1.Coordinates
	1, // 1: driversstate.v1.TripOffer.drop_off:type_name -> common.geo.v1.Coordinates
	2, // 2: driversstate.v1.TripOffer.expires_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_driverspb_drivers_messages_proto_init() }
func file_driverspb_drivers_messages_proto_init() {
	if File_driverspb_drivers_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_driverspb_drivers_messages_proto_rawDesc), len(file_driverspb_drivers_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_driverspb_drivers_messages_proto_goTypes,
		DependencyIndexes: file_driverspb_drivers_messages_proto_depIdxs,
		MessageInfos:      file_driverspb_drivers_messages_proto_msgTypes,
	}.Build()
	File_driverspb_drivers_messages_proto = out.File
	file_driverspb_drivers_messages_proto_goTypes = nil
	file_driverspb_drivers_messages_proto_depIdxs = nil
}
