// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: riderspb/riders_messages.proto

package riderspb

import (
	common "github.com/Binit-Dhakal/Saarathi/pkg/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RiderUpdatePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	DriverName    string                 `protobuf:"bytes,2,opt,name=driver_name,json=driverName,proto3" json:"driver_name,omitempty"`
	VehicleMake   string                 `protobuf:"bytes,3,opt,name=vehicle_make,json=vehicleMake,proto3" json:"vehicle_make,omitempty"`
	VehicleModel  string                 `protobuf:"bytes,4,opt,name=vehicle_model,json=vehicleModel,proto3" json:"vehicle_model,omitempty"`
	VehicleNumber string                 `protobuf:"bytes,5,opt,name=vehicle_number,json=vehicleNumber,proto3" json:"vehicle_number,omitempty"`
	DriverLoc     *common.Coordinates    `protobuf:"bytes,6,opt,name=driver_loc,json=driverLoc,proto3" json:"driver_loc,omitempty"`
	Pickup        *common.Coordinates    `protobuf:"bytes,7,opt,name=pickup,proto3" json:"pickup,omitempty"`
	Dropoff       *common.Coordinates    `protobuf:"bytes,8,opt,name=dropoff,proto3" json:"dropoff,omitempty"`
	Price         int32                  `protobuf:"varint,9,opt,name=price,proto3" json:"price,omitempty"`
	Distance      float64                `protobuf:"fixed64,10,opt,name=distance,proto3" json:"distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiderUpdatePayload) Reset() {
	*x = RiderUpdatePayload{}
	mi := &file_riderspb_riders_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiderUpdatePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiderUpdatePayload) ProtoMessage() {}

func (x *RiderUpdatePayload) ProtoReflect() protoreflect.Message {
	mi := &file_riderspb_riders_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiderUpdatePayload.ProtoReflect.Descriptor instead.
func (*RiderUpdatePayload) Descriptor() ([]byte, []int) {
	return file_riderspb_riders_messages_proto_rawDescGZIP(), []int{0}
}

func (x *RiderUpdatePayload) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *RiderUpdatePayload) GetDriverName() string {
	if x != nil {
		return x.DriverName
	}
	return ""
}

func (x *RiderUpdatePayload) GetVehicleMake() string {
	if x != nil {
		return x.VehicleMake
	}
	return ""
}

func (x *RiderUpdatePayload) GetVehicleModel() string {
	if x != nil {
		return x.VehicleModel
	}
	return ""
}

func (x *RiderUpdatePayload) GetVehicleNumber() string {
	if x != nil {
		return x.VehicleNumber
	}
	return ""
}

func (x *RiderUpdatePayload) GetDriverLoc() *common.Coordinates {
	if x != nil {
		return x.DriverLoc
	}
	return nil
}

func (x *RiderUpdatePayload) GetPickup() *common.Coordinates {
	if x != nil {
		return x.Pickup
	}
	return nil
}

func (x *RiderUpdatePayload) GetDropoff() *common.Coordinates {
	if x != nil {
		return x.Dropoff
	}
	return nil
}

func (x *RiderUpdatePayload) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *RiderUpdatePayload) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

var File_riderspb_riders_messages_proto protoreflect.FileDescriptor

const file_riderspb_riders_messages_proto_rawDesc = "" +
	"\n" +
	"\x1eriderspb/riders_messages.proto\x12\x0eridersstate.v1\x1a\x10common/geo.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x94\x03\n" +
	"\x12RiderUpdatePayload\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x1f\n" +
	"\vdriver_name\x18\x02 \x01(\tR\n" +
	"driverName\x12!\n" +
	"\fvehicle_make\x18\x03 \x01(\tR\vvehicleMake\x12#\n" +
	"\rvehicle_model\x18\x04 \x01(\tR\fvehicleModel\x12%\n" +
	"\x0evehicle_number\x18\x05 \x01(\tR\rvehicleNumber\x129\n" +
	"\n" +
	"driver_loc\x18\x06 \x01(\v2\x1a.common.geo.v1.CoordinatesR\tdriverLoc\x122\n" +
	"\x06pickup\x18\a \x01(\v2\x1a.common.geo.v1.CoordinatesR\x06pickup\x124\n" +
	"\adropoff\x18\b \x01(\v2\x1a.common.geo.v1.CoordinatesR\adropoff\x12\x14\n" +
	"\x05price\x18\t \x01(\x05R\x05price\x12\x1a\n" +
	"\bdistance\x18\n" +
	" \x01(\x01R\bdistanceB=Z;github.com/Binit-Dhakal/Saarathi/pkg/contracts/dto/riderspbb\x06proto3"

var (
	file_riderspb_riders_messages_proto_rawDescOnce sync.Once
	file_riderspb_riders_messages_proto_rawDescData []byte
)

func file_riderspb_riders_messages_proto_rawDescGZIP() []byte {
	file_riderspb_riders_messages_proto_rawDescOnce.Do(func() {
		file_riderspb_riders_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_riderspb_riders_messages_proto_rawDesc), len(file_riderspb_riders_messages_proto_rawDesc)))
	})
	return file_riderspb_riders_messages_proto_rawDescData
}

var file_riderspb_riders_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_riderspb_riders_messages_proto_goTypes = []any{
	(*RiderUpdatePayload)(nil), // 0: ridersstate.v1.RiderUpdatePayload
	(*common.Coordinates)(nil), // 1: common.geo.v1.Coordinates
}
var file_riderspb_riders_messages_proto_depIdxs = []int32{
	1, // 0: ridersstate.v1.RiderUpdatePayload.driver_loc:type_name -> common.geo.v1.Coordinates
	1, // 1: ridersstate.v1.RiderUpdatePayload.pickup:type_name -> common.geo.v1.Coordinates
	1, // 2: ridersstate.v1.RiderUpdatePayload.dropoff:type_name -> common.geo.v1.Coordinates
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_riderspb_riders_messages_proto_init() }
func file_riderspb_riders_messages_proto_init() {
	if File_riderspb_riders_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_riderspb_riders_messages_proto_rawDesc), len(file_riderspb_riders_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_riderspb_riders_messages_proto_goTypes,
		DependencyIndexes: file_riderspb_riders_messages_proto_depIdxs,
		MessageInfos:      file_riderspb_riders_messages_proto_msgTypes,
	}.Build()
	File_riderspb_riders_messages_proto = out.File
	file_riderspb_riders_messages_proto_goTypes = nil
	file_riderspb_riders_messages_proto_depIdxs = nil
}
