# .air.toml — Air config for hot reload
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/trips-service ./cmd/main.go"
bin = "tmp/trips-service"
full_bin = ""
include_ext = ["go"]
exclude_dir = ["tmp", "vendor"]

[log]
timestamp = true

