apiVersion: v1
kind: PersistentVolume
metadata:
  name: osrm-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /data/osrm   # must exist on the Kind node

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: osrm-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: osrm-backend
spec:
  template:
    spec:
      volumes:
        - name: osrm-data
          persistentVolumeClaim:
            claimName: osrm-pvc
