// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: proto/trip/trip.proto

package tripsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TripCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	Distance      float64                `protobuf:"fixed64,2,opt,name=distance,proto3" json:"distance,omitempty"`
	Price         int32                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	PickUp        *Coordinates           `protobuf:"bytes,4,opt,name=pick_up,json=pickUp,proto3" json:"pick_up,omitempty"`
	DropOff       *Coordinates           `protobuf:"bytes,5,opt,name=drop_off,json=dropOff,proto3" json:"drop_off,omitempty"`
	CarType       string                 `protobuf:"bytes,6,opt,name=car_type,json=carType,proto3" json:"car_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TripCreated) Reset() {
	*x = TripCreated{}
	mi := &file_proto_trip_trip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripCreated) ProtoMessage() {}

func (x *TripCreated) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trip_trip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripCreated.ProtoReflect.Descriptor instead.
func (*TripCreated) Descriptor() ([]byte, []int) {
	return file_proto_trip_trip_proto_rawDescGZIP(), []int{0}
}

func (x *TripCreated) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *TripCreated) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *TripCreated) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TripCreated) GetPickUp() *Coordinates {
	if x != nil {
		return x.PickUp
	}
	return nil
}

func (x *TripCreated) GetDropOff() *Coordinates {
	if x != nil {
		return x.DropOff
	}
	return nil
}

func (x *TripCreated) GetCarType() string {
	if x != nil {
		return x.CarType
	}
	return ""
}

type Coordinates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinates) Reset() {
	*x = Coordinates{}
	mi := &file_proto_trip_trip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinates) ProtoMessage() {}

func (x *Coordinates) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trip_trip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinates.ProtoReflect.Descriptor instead.
func (*Coordinates) Descriptor() ([]byte, []int) {
	return file_proto_trip_trip_proto_rawDescGZIP(), []int{1}
}

func (x *Coordinates) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Coordinates) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

var File_proto_trip_trip_proto protoreflect.FileDescriptor

const file_proto_trip_trip_proto_rawDesc = "" +
	"\n" +
	"\x15proto/trip/trip.proto\x12\btrips.v1\"\xd5\x01\n" +
	"\vTripCreated\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x1a\n" +
	"\bdistance\x18\x02 \x01(\x01R\bdistance\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price\x12.\n" +
	"\apick_up\x18\x04 \x01(\v2\x15.trips.v1.CoordinatesR\x06pickUp\x120\n" +
	"\bdrop_off\x18\x05 \x01(\v2\x15.trips.v1.CoordinatesR\adropOff\x12\x19\n" +
	"\bcar_type\x18\x06 \x01(\tR\acarType\"1\n" +
	"\vCoordinates\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lngB\x97\x01\n" +
	"\fcom.trips.v1B\tTripProtoP\x01Z;github.com/Binit-Dhakal/Saarathi/tripspb/proto/trip;tripsv1\xa2\x02\x03TXX\xaa\x02\bTrips.V1\xca\x02\bTrips\\V1\xe2\x02\x14Trips\\V1\\GPBMetadata\xea\x02\tTrips::V1b\x06proto3"

var (
	file_proto_trip_trip_proto_rawDescOnce sync.Once
	file_proto_trip_trip_proto_rawDescData []byte
)

func file_proto_trip_trip_proto_rawDescGZIP() []byte {
	file_proto_trip_trip_proto_rawDescOnce.Do(func() {
		file_proto_trip_trip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_trip_trip_proto_rawDesc), len(file_proto_trip_trip_proto_rawDesc)))
	})
	return file_proto_trip_trip_proto_rawDescData
}

var file_proto_trip_trip_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_trip_trip_proto_goTypes = []any{
	(*TripCreated)(nil), // 0: trips.v1.TripCreated
	(*Coordinates)(nil), // 1: trips.v1.Coordinates
}
var file_proto_trip_trip_proto_depIdxs = []int32{
	1, // 0: trips.v1.TripCreated.pick_up:type_name -> trips.v1.Coordinates
	1, // 1: trips.v1.TripCreated.drop_off:type_name -> trips.v1.Coordinates
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_trip_trip_proto_init() }
func file_proto_trip_trip_proto_init() {
	if File_proto_trip_trip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_trip_trip_proto_rawDesc), len(file_proto_trip_trip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_trip_trip_proto_goTypes,
		DependencyIndexes: file_proto_trip_trip_proto_depIdxs,
		MessageInfos:      file_proto_trip_trip_proto_msgTypes,
	}.Build()
	File_proto_trip_trip_proto = out.File
	file_proto_trip_trip_proto_goTypes = nil
	file_proto_trip_trip_proto_depIdxs = nil
}
