apiVersion: v1
kind: Service
metadata:
  name: trips-service
  labels:
    app: trips
spec:
  type: ClusterIP
  selector:
    app: trips
  ports:
    - name: http
      port: 8070
      targetPort: 8070
