apiVersion: apps/v1
kind: Deployment
metadata:
  name:  ride-matching
  labels:
    app: ride-matching 
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: ride-matching
  template:
    metadata:
      labels:
        app: ride-matching 
    spec:
      containers:
        - name: ride-matching
          image: ride-matching-service
          imagePullPolicy: IfNotPresent
          ports: 
            - containerPort: 8060
          envFrom:
            - secretRef:
                name: ride-matching-secrets
          env:  
            - name: ENVIRONMENT
              value: local 
            - name: LOG_LEVEL
              value: DEBUG
            - name: SHUTDOWN_TIMEOUT
              value: "30s"
          volumeMounts:
            - name: tmp-volume
              mountPath: /app/trips/tmp

      volumes:
        - name: tmp-volume
          emptyDir: {}
