// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: core_message.proto

package natscore

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CoreMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreMessage) Reset() {
	*x = CoreMessage{}
	mi := &file_core_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreMessage) ProtoMessage() {}

func (x *CoreMessage) ProtoReflect() protoreflect.Message {
	mi := &file_core_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreMessage.ProtoReflect.Descriptor instead.
func (*CoreMessage) Descriptor() ([]byte, []int) {
	return file_core_message_proto_rawDescGZIP(), []int{0}
}

func (x *CoreMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CoreMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CoreMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_core_message_proto protoreflect.FileDescriptor

const file_core_message_proto_rawDesc = "" +
	"\n" +
	"\x12core_message.proto\x12\bnatscore\"E\n" +
	"\vCoreMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04dataB\x8f\x01\n" +
	"\fcom.natscoreB\x10CoreMessageProtoP\x01Z-github.com/Binit-Dhakal/Saarathi/pkg/natscore\xa2\x02\x03NXX\xaa\x02\bNatscore\xca\x02\bNatscore\xe2\x02\x14Natscore\\GPBMetadata\xea\x02\bNatscoreb\x06proto3"

var (
	file_core_message_proto_rawDescOnce sync.Once
	file_core_message_proto_rawDescData []byte
)

func file_core_message_proto_rawDescGZIP() []byte {
	file_core_message_proto_rawDescOnce.Do(func() {
		file_core_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_message_proto_rawDesc), len(file_core_message_proto_rawDesc)))
	})
	return file_core_message_proto_rawDescData
}

var file_core_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_core_message_proto_goTypes = []any{
	(*CoreMessage)(nil), // 0: natscore.CoreMessage
}
var file_core_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_message_proto_init() }
func file_core_message_proto_init() {
	if File_core_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_message_proto_rawDesc), len(file_core_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_message_proto_goTypes,
		DependencyIndexes: file_core_message_proto_depIdxs,
		MessageInfos:      file_core_message_proto_msgTypes,
	}.Build()
	File_core_message_proto = out.File
	file_core_message_proto_goTypes = nil
	file_core_message_proto_depIdxs = nil
}
