// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: projections/projection.proto

package projectionspb

import (
	common "github.com/Binit-Dhakal/Saarathi/pkg/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TripProjectionV1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Rider Details
	RiderId    string `protobuf:"bytes,1,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	RiderName  string `protobuf:"bytes,2,opt,name=rider_name,json=riderName,proto3" json:"rider_name,omitempty"`
	RiderPhone string `protobuf:"bytes,3,opt,name=rider_phone,json=riderPhone,proto3" json:"rider_phone,omitempty"`
	// Driver Details
	DriverId       string              `protobuf:"bytes,4,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	DriverName     string              `protobuf:"bytes,5,opt,name=driver_name,json=driverName,proto3" json:"driver_name,omitempty"`
	DriverPhone    string              `protobuf:"bytes,6,opt,name=driver_phone,json=driverPhone,proto3" json:"driver_phone,omitempty"`
	VehicleMake    string              `protobuf:"bytes,7,opt,name=vehicle_make,json=vehicleMake,proto3" json:"vehicle_make,omitempty"`
	VehicleModel   string              `protobuf:"bytes,8,opt,name=vehicle_model,json=vehicleModel,proto3" json:"vehicle_model,omitempty"`
	LicenseNumber  string              `protobuf:"bytes,9,opt,name=license_number,json=licenseNumber,proto3" json:"license_number,omitempty"`
	VehicleNumber  string              `protobuf:"bytes,10,opt,name=vehicle_number,json=vehicleNumber,proto3" json:"vehicle_number,omitempty"`
	DriverLocation *common.Coordinates `protobuf:"bytes,11,opt,name=driver_location,json=driverLocation,proto3" json:"driver_location,omitempty"`
	// Trip Details
	TripId        string              `protobuf:"bytes,12,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	Pickup        *common.Coordinates `protobuf:"bytes,13,opt,name=pickup,proto3" json:"pickup,omitempty"`
	Dropoff       *common.Coordinates `protobuf:"bytes,14,opt,name=dropoff,proto3" json:"dropoff,omitempty"`
	Distance      float64             `protobuf:"fixed64,15,opt,name=distance,proto3" json:"distance,omitempty"`
	FarePrice     int32               `protobuf:"varint,16,opt,name=fare_price,json=farePrice,proto3" json:"fare_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TripProjectionV1) Reset() {
	*x = TripProjectionV1{}
	mi := &file_projections_projection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripProjectionV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripProjectionV1) ProtoMessage() {}

func (x *TripProjectionV1) ProtoReflect() protoreflect.Message {
	mi := &file_projections_projection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripProjectionV1.ProtoReflect.Descriptor instead.
func (*TripProjectionV1) Descriptor() ([]byte, []int) {
	return file_projections_projection_proto_rawDescGZIP(), []int{0}
}

func (x *TripProjectionV1) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *TripProjectionV1) GetRiderName() string {
	if x != nil {
		return x.RiderName
	}
	return ""
}

func (x *TripProjectionV1) GetRiderPhone() string {
	if x != nil {
		return x.RiderPhone
	}
	return ""
}

func (x *TripProjectionV1) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *TripProjectionV1) GetDriverName() string {
	if x != nil {
		return x.DriverName
	}
	return ""
}

func (x *TripProjectionV1) GetDriverPhone() string {
	if x != nil {
		return x.DriverPhone
	}
	return ""
}

func (x *TripProjectionV1) GetVehicleMake() string {
	if x != nil {
		return x.VehicleMake
	}
	return ""
}

func (x *TripProjectionV1) GetVehicleModel() string {
	if x != nil {
		return x.VehicleModel
	}
	return ""
}

func (x *TripProjectionV1) GetLicenseNumber() string {
	if x != nil {
		return x.LicenseNumber
	}
	return ""
}

func (x *TripProjectionV1) GetVehicleNumber() string {
	if x != nil {
		return x.VehicleNumber
	}
	return ""
}

func (x *TripProjectionV1) GetDriverLocation() *common.Coordinates {
	if x != nil {
		return x.DriverLocation
	}
	return nil
}

func (x *TripProjectionV1) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *TripProjectionV1) GetPickup() *common.Coordinates {
	if x != nil {
		return x.Pickup
	}
	return nil
}

func (x *TripProjectionV1) GetDropoff() *common.Coordinates {
	if x != nil {
		return x.Dropoff
	}
	return nil
}

func (x *TripProjectionV1) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *TripProjectionV1) GetFarePrice() int32 {
	if x != nil {
		return x.FarePrice
	}
	return 0
}

var File_projections_projection_proto protoreflect.FileDescriptor

const file_projections_projection_proto_rawDesc = "" +
	"\n" +
	"\x1cprojections/projection.proto\x12\x10projectionspb.v1\x1a\x10common/geo.proto\"\xe7\x04\n" +
	"\x10TripProjectionV1\x12\x19\n" +
	"\brider_id\x18\x01 \x01(\tR\ariderId\x12\x1d\n" +
	"\n" +
	"rider_name\x18\x02 \x01(\tR\triderName\x12\x1f\n" +
	"\vrider_phone\x18\x03 \x01(\tR\n" +
	"riderPhone\x12\x1b\n" +
	"\tdriver_id\x18\x04 \x01(\tR\bdriverId\x12\x1f\n" +
	"\vdriver_name\x18\x05 \x01(\tR\n" +
	"driverName\x12!\n" +
	"\fdriver_phone\x18\x06 \x01(\tR\vdriverPhone\x12!\n" +
	"\fvehicle_make\x18\a \x01(\tR\vvehicleMake\x12#\n" +
	"\rvehicle_model\x18\b \x01(\tR\fvehicleModel\x12%\n" +
	"\x0elicense_number\x18\t \x01(\tR\rlicenseNumber\x12%\n" +
	"\x0evehicle_number\x18\n" +
	" \x01(\tR\rvehicleNumber\x12C\n" +
	"\x0fdriver_location\x18\v \x01(\v2\x1a.common.geo.v1.CoordinatesR\x0edriverLocation\x12\x17\n" +
	"\atrip_id\x18\f \x01(\tR\x06tripId\x122\n" +
	"\x06pickup\x18\r \x01(\v2\x1a.common.geo.v1.CoordinatesR\x06pickup\x124\n" +
	"\adropoff\x18\x0e \x01(\v2\x1a.common.geo.v1.CoordinatesR\adropoff\x12\x1a\n" +
	"\bdistance\x18\x0f \x01(\x01R\bdistance\x12\x1d\n" +
	"\n" +
	"fare_price\x18\x10 \x01(\x05R\tfarePriceB:Z8github.com/Binit-Dhakal/Saarathi/pkg/proto/projectionspbb\x06proto3"

var (
	file_projections_projection_proto_rawDescOnce sync.Once
	file_projections_projection_proto_rawDescData []byte
)

func file_projections_projection_proto_rawDescGZIP() []byte {
	file_projections_projection_proto_rawDescOnce.Do(func() {
		file_projections_projection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_projections_projection_proto_rawDesc), len(file_projections_projection_proto_rawDesc)))
	})
	return file_projections_projection_proto_rawDescData
}

var file_projections_projection_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_projections_projection_proto_goTypes = []any{
	(*TripProjectionV1)(nil),   // 0: projectionspb.v1.TripProjectionV1
	(*common.Coordinates)(nil), // 1: common.geo.v1.Coordinates
}
var file_projections_projection_proto_depIdxs = []int32{
	1, // 0: projectionspb.v1.TripProjectionV1.driver_location:type_name -> common.geo.v1.Coordinates
	1, // 1: projectionspb.v1.TripProjectionV1.pickup:type_name -> common.geo.v1.Coordinates
	1, // 2: projectionspb.v1.TripProjectionV1.dropoff:type_name -> common.geo.v1.Coordinates
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_projections_projection_proto_init() }
func file_projections_projection_proto_init() {
	if File_projections_projection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_projections_projection_proto_rawDesc), len(file_projections_projection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_projections_projection_proto_goTypes,
		DependencyIndexes: file_projections_projection_proto_depIdxs,
		MessageInfos:      file_projections_projection_proto_msgTypes,
	}.Build()
	File_projections_projection_proto = out.File
	file_projections_projection_proto_goTypes = nil
	file_projections_projection_proto_depIdxs = nil
}
