// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: userspb/api.proto

package userspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRiderDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRiderDetailsRequest) Reset() {
	*x = GetRiderDetailsRequest{}
	mi := &file_userspb_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRiderDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRiderDetailsRequest) ProtoMessage() {}

func (x *GetRiderDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userspb_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRiderDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetRiderDetailsRequest) Descriptor() ([]byte, []int) {
	return file_userspb_api_proto_rawDescGZIP(), []int{0}
}

func (x *GetRiderDetailsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRiderDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRiderDetailsResponse) Reset() {
	*x = GetRiderDetailsResponse{}
	mi := &file_userspb_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRiderDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRiderDetailsResponse) ProtoMessage() {}

func (x *GetRiderDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userspb_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRiderDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetRiderDetailsResponse) Descriptor() ([]byte, []int) {
	return file_userspb_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetRiderDetailsResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetRiderDetailsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetRiderDetailsResponse) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type GetDriverDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverDetailsRequest) Reset() {
	*x = GetDriverDetailsRequest{}
	mi := &file_userspb_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverDetailsRequest) ProtoMessage() {}

func (x *GetDriverDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userspb_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetDriverDetailsRequest) Descriptor() ([]byte, []int) {
	return file_userspb_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetDriverDetailsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDriverDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	LicenseNumber string                 `protobuf:"bytes,4,opt,name=license_number,json=licenseNumber,proto3" json:"license_number,omitempty"`
	VehicleMake   string                 `protobuf:"bytes,5,opt,name=vehicle_make,json=vehicleMake,proto3" json:"vehicle_make,omitempty"`
	VehicleModel  string                 `protobuf:"bytes,6,opt,name=vehicle_model,json=vehicleModel,proto3" json:"vehicle_model,omitempty"`
	VehiclePlate  string                 `protobuf:"bytes,7,opt,name=vehicle_plate,json=vehiclePlate,proto3" json:"vehicle_plate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverDetailsResponse) Reset() {
	*x = GetDriverDetailsResponse{}
	mi := &file_userspb_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverDetailsResponse) ProtoMessage() {}

func (x *GetDriverDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userspb_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetDriverDetailsResponse) Descriptor() ([]byte, []int) {
	return file_userspb_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetDriverDetailsResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetDriverDetailsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetDriverDetailsResponse) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *GetDriverDetailsResponse) GetLicenseNumber() string {
	if x != nil {
		return x.LicenseNumber
	}
	return ""
}

func (x *GetDriverDetailsResponse) GetVehicleMake() string {
	if x != nil {
		return x.VehicleMake
	}
	return ""
}

func (x *GetDriverDetailsResponse) GetVehicleModel() string {
	if x != nil {
		return x.VehicleModel
	}
	return ""
}

func (x *GetDriverDetailsResponse) GetVehiclePlate() string {
	if x != nil {
		return x.VehiclePlate
	}
	return ""
}

var File_userspb_api_proto protoreflect.FileDescriptor

const file_userspb_api_proto_rawDesc = "" +
	"\n" +
	"\x11userspb/api.proto\x12\auserspb\"(\n" +
	"\x16GetRiderDetailsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"`\n" +
	"\x17GetRiderDetailsResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\")\n" +
	"\x17GetDriverDetailsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xf5\x01\n" +
	"\x18GetDriverDetailsResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\x12%\n" +
	"\x0elicense_number\x18\x04 \x01(\tR\rlicenseNumber\x12!\n" +
	"\fvehicle_make\x18\x05 \x01(\tR\vvehicleMake\x12#\n" +
	"\rvehicle_model\x18\x06 \x01(\tR\fvehicleModel\x12#\n" +
	"\rvehicle_plate\x18\a \x01(\tR\fvehiclePlate2\xbd\x01\n" +
	"\fUsersService\x12T\n" +
	"\x0fGetRiderDetails\x12\x1f.userspb.GetRiderDetailsRequest\x1a .userspb.GetRiderDetailsResponse\x12W\n" +
	"\x10GetDriverDetails\x12 .userspb.GetDriverDetailsRequest\x1a!.userspb.GetDriverDetailsResponseB4Z2github.com/Binit-Dhakal/Saarathi/pkg/proto/userspbb\x06proto3"

var (
	file_userspb_api_proto_rawDescOnce sync.Once
	file_userspb_api_proto_rawDescData []byte
)

func file_userspb_api_proto_rawDescGZIP() []byte {
	file_userspb_api_proto_rawDescOnce.Do(func() {
		file_userspb_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_userspb_api_proto_rawDesc), len(file_userspb_api_proto_rawDesc)))
	})
	return file_userspb_api_proto_rawDescData
}

var file_userspb_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_userspb_api_proto_goTypes = []any{
	(*GetRiderDetailsRequest)(nil),   // 0: userspb.GetRiderDetailsRequest
	(*GetRiderDetailsResponse)(nil),  // 1: userspb.GetRiderDetailsResponse
	(*GetDriverDetailsRequest)(nil),  // 2: userspb.GetDriverDetailsRequest
	(*GetDriverDetailsResponse)(nil), // 3: userspb.GetDriverDetailsResponse
}
var file_userspb_api_proto_depIdxs = []int32{
	0, // 0: userspb.UsersService.GetRiderDetails:input_type -> userspb.GetRiderDetailsRequest
	2, // 1: userspb.UsersService.GetDriverDetails:input_type -> userspb.GetDriverDetailsRequest
	1, // 2: userspb.UsersService.GetRiderDetails:output_type -> userspb.GetRiderDetailsResponse
	3, // 3: userspb.UsersService.GetDriverDetails:output_type -> userspb.GetDriverDetailsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_userspb_api_proto_init() }
func file_userspb_api_proto_init() {
	if File_userspb_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_userspb_api_proto_rawDesc), len(file_userspb_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_userspb_api_proto_goTypes,
		DependencyIndexes: file_userspb_api_proto_depIdxs,
		MessageInfos:      file_userspb_api_proto_msgTypes,
	}.Build()
	File_userspb_api_proto = out.File
	file_userspb_api_proto_goTypes = nil
	file_userspb_api_proto_depIdxs = nil
}
