apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  labels:
    app: users
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels: 
        app: users
    spec:
      containers:
        - name: users
          image: users-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090
          envFrom:
            - secretRef:
                name: users-secrets
          env:
            - name: ENVIRONMENT
              value: local
            - name: LOG_LEVEL
              value: DEBUG
          volumeMounts:
            - name: tmp-volume
              mountPath: /apps/users/tmp

      volumes:
        - name: tmp-volume
          emptyDir: {}
