apiVersion: v1
kind: Service
metadata:
  name: users-service
  labels:
    app: users
spec:
  type: ClusterIP
  selector: 
    app: users
  ports:
    - name: http
      port: 8090
      targetPort: 8090
