// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: rmspb/ride_matching.proto

package rmspb

import (
	_ "github.com/Binit-Dhakal/Saarathi/pkg/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CandidatesMatched struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SagaId            string                 `protobuf:"bytes,1,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	TripId            string                 `protobuf:"bytes,2,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	DriverIds         []string               `protobuf:"bytes,3,rep,name=driver_ids,json=driverIds,proto3" json:"driver_ids,omitempty"`
	MaxSearchRadiusKm int32                  `protobuf:"varint,4,opt,name=max_search_radius_km,json=maxSearchRadiusKm,proto3" json:"max_search_radius_km,omitempty"`
	Attempt           int32                  `protobuf:"varint,5,opt,name=attempt,proto3" json:"attempt,omitempty"`
	FirstAttemptUnix  int64                  `protobuf:"varint,8,opt,name=first_attempt_unix,json=firstAttemptUnix,proto3" json:"first_attempt_unix,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CandidatesMatched) Reset() {
	*x = CandidatesMatched{}
	mi := &file_rmspb_ride_matching_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidatesMatched) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidatesMatched) ProtoMessage() {}

func (x *CandidatesMatched) ProtoReflect() protoreflect.Message {
	mi := &file_rmspb_ride_matching_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidatesMatched.ProtoReflect.Descriptor instead.
func (*CandidatesMatched) Descriptor() ([]byte, []int) {
	return file_rmspb_ride_matching_proto_rawDescGZIP(), []int{0}
}

func (x *CandidatesMatched) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

func (x *CandidatesMatched) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *CandidatesMatched) GetDriverIds() []string {
	if x != nil {
		return x.DriverIds
	}
	return nil
}

func (x *CandidatesMatched) GetMaxSearchRadiusKm() int32 {
	if x != nil {
		return x.MaxSearchRadiusKm
	}
	return 0
}

func (x *CandidatesMatched) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *CandidatesMatched) GetFirstAttemptUnix() int64 {
	if x != nil {
		return x.FirstAttemptUnix
	}
	return 0
}

var File_rmspb_ride_matching_proto protoreflect.FileDescriptor

const file_rmspb_ride_matching_proto_rawDesc = "" +
	"\n" +
	"\x19rmspb/ride_matching.proto\x12\x0fridematching.v1\x1a\x10common/geo.proto\"\xdd\x01\n" +
	"\x11CandidatesMatched\x12\x17\n" +
	"\asaga_id\x18\x01 \x01(\tR\x06sagaId\x12\x17\n" +
	"\atrip_id\x18\x02 \x01(\tR\x06tripId\x12\x1d\n" +
	"\n" +
	"driver_ids\x18\x03 \x03(\tR\tdriverIds\x12/\n" +
	"\x14max_search_radius_km\x18\x04 \x01(\x05R\x11maxSearchRadiusKm\x12\x18\n" +
	"\aattempt\x18\x05 \x01(\x05R\aattempt\x12,\n" +
	"\x12first_attempt_unix\x18\b \x01(\x03R\x10firstAttemptUnixB2Z0github.com/Binit-Dhakal/Saarathi/pkg/proto/rmspbb\x06proto3"

var (
	file_rmspb_ride_matching_proto_rawDescOnce sync.Once
	file_rmspb_ride_matching_proto_rawDescData []byte
)

func file_rmspb_ride_matching_proto_rawDescGZIP() []byte {
	file_rmspb_ride_matching_proto_rawDescOnce.Do(func() {
		file_rmspb_ride_matching_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rmspb_ride_matching_proto_rawDesc), len(file_rmspb_ride_matching_proto_rawDesc)))
	})
	return file_rmspb_ride_matching_proto_rawDescData
}

var file_rmspb_ride_matching_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rmspb_ride_matching_proto_goTypes = []any{
	(*CandidatesMatched)(nil), // 0: ridematching.v1.CandidatesMatched
}
var file_rmspb_ride_matching_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rmspb_ride_matching_proto_init() }
func file_rmspb_ride_matching_proto_init() {
	if File_rmspb_ride_matching_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rmspb_ride_matching_proto_rawDesc), len(file_rmspb_ride_matching_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rmspb_ride_matching_proto_goTypes,
		DependencyIndexes: file_rmspb_ride_matching_proto_depIdxs,
		MessageInfos:      file_rmspb_ride_matching_proto_msgTypes,
	}.Build()
	File_rmspb_ride_matching_proto = out.File
	file_rmspb_ride_matching_proto_goTypes = nil
	file_rmspb_ride_matching_proto_depIdxs = nil
}
