// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/offerspb/offer.proto

package offerspb

import (
	common "github.com/Binit-Dhakal/Saarathi/pkg/contracts/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RideMatchingRequested struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SagaId            string                 `protobuf:"bytes,1,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	TripId            string                 `protobuf:"bytes,2,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	PickUp            *common.Coordinates    `protobuf:"bytes,3,opt,name=pick_up,json=pickUp,proto3" json:"pick_up,omitempty"`
	DropOff           *common.Coordinates    `protobuf:"bytes,4,opt,name=drop_off,json=dropOff,proto3" json:"drop_off,omitempty"`
	CarType           string                 `protobuf:"bytes,5,opt,name=car_type,json=carType,proto3" json:"car_type,omitempty"`
	MaxSearchRadiusKm float64                `protobuf:"fixed64,6,opt,name=max_search_radius_km,json=maxSearchRadiusKm,proto3" json:"max_search_radius_km,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RideMatchingRequested) Reset() {
	*x = RideMatchingRequested{}
	mi := &file_proto_offerspb_offer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RideMatchingRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RideMatchingRequested) ProtoMessage() {}

func (x *RideMatchingRequested) ProtoReflect() protoreflect.Message {
	mi := &file_proto_offerspb_offer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RideMatchingRequested.ProtoReflect.Descriptor instead.
func (*RideMatchingRequested) Descriptor() ([]byte, []int) {
	return file_proto_offerspb_offer_proto_rawDescGZIP(), []int{0}
}

func (x *RideMatchingRequested) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

func (x *RideMatchingRequested) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *RideMatchingRequested) GetPickUp() *common.Coordinates {
	if x != nil {
		return x.PickUp
	}
	return nil
}

func (x *RideMatchingRequested) GetDropOff() *common.Coordinates {
	if x != nil {
		return x.DropOff
	}
	return nil
}

func (x *RideMatchingRequested) GetCarType() string {
	if x != nil {
		return x.CarType
	}
	return ""
}

func (x *RideMatchingRequested) GetMaxSearchRadiusKm() float64 {
	if x != nil {
		return x.MaxSearchRadiusKm
	}
	return 0
}

type TripOfferRequested struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SagaId        string                 `protobuf:"bytes,1,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	TripId        string                 `protobuf:"bytes,2,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	Price         int32                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Distance      float64                `protobuf:"fixed64,4,opt,name=distance,proto3" json:"distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TripOfferRequested) Reset() {
	*x = TripOfferRequested{}
	mi := &file_proto_offerspb_offer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripOfferRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripOfferRequested) ProtoMessage() {}

func (x *TripOfferRequested) ProtoReflect() protoreflect.Message {
	mi := &file_proto_offerspb_offer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripOfferRequested.ProtoReflect.Descriptor instead.
func (*TripOfferRequested) Descriptor() ([]byte, []int) {
	return file_proto_offerspb_offer_proto_rawDescGZIP(), []int{1}
}

func (x *TripOfferRequested) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

func (x *TripOfferRequested) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *TripOfferRequested) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TripOfferRequested) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

var File_proto_offerspb_offer_proto protoreflect.FileDescriptor

const file_proto_offerspb_offer_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/offerspb/offer.proto\x12\toffers.v1\x1a\x16proto/common/geo.proto\"\x81\x02\n" +
	"\x15RideMatchingRequested\x12\x17\n" +
	"\asaga_id\x18\x01 \x01(\tR\x06sagaId\x12\x17\n" +
	"\atrip_id\x18\x02 \x01(\tR\x06tripId\x123\n" +
	"\apick_up\x18\x03 \x01(\v2\x1a.common.geo.v1.CoordinatesR\x06pickUp\x125\n" +
	"\bdrop_off\x18\x04 \x01(\v2\x1a.common.geo.v1.CoordinatesR\adropOff\x12\x19\n" +
	"\bcar_type\x18\x05 \x01(\tR\acarType\x12/\n" +
	"\x14max_search_radius_km\x18\x06 \x01(\x01R\x11maxSearchRadiusKm\"x\n" +
	"\x12TripOfferRequested\x12\x17\n" +
	"\asaga_id\x18\x01 \x01(\tR\x06sagaId\x12\x17\n" +
	"\atrip_id\x18\x02 \x01(\tR\x06tripId\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price\x12\x1a\n" +
	"\bdistance\x18\x04 \x01(\x01R\bdistanceB?Z=github.com/Binit-Dhakal/Saarathi/pkg/contracts/proto/offerspbb\x06proto3"

var (
	file_proto_offerspb_offer_proto_rawDescOnce sync.Once
	file_proto_offerspb_offer_proto_rawDescData []byte
)

func file_proto_offerspb_offer_proto_rawDescGZIP() []byte {
	file_proto_offerspb_offer_proto_rawDescOnce.Do(func() {
		file_proto_offerspb_offer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_offerspb_offer_proto_rawDesc), len(file_proto_offerspb_offer_proto_rawDesc)))
	})
	return file_proto_offerspb_offer_proto_rawDescData
}

var file_proto_offerspb_offer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_offerspb_offer_proto_goTypes = []any{
	(*RideMatchingRequested)(nil), // 0: offers.v1.RideMatchingRequested
	(*TripOfferRequested)(nil),    // 1: offers.v1.TripOfferRequested
	(*common.Coordinates)(nil),    // 2: common.geo.v1.Coordinates
}
var file_proto_offerspb_offer_proto_depIdxs = []int32{
	2, // 0: offers.v1.RideMatchingRequested.pick_up:type_name -> common.geo.v1.Coordinates
	2, // 1: offers.v1.RideMatchingRequested.drop_off:type_name -> common.geo.v1.Coordinates
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_offerspb_offer_proto_init() }
func file_proto_offerspb_offer_proto_init() {
	if File_proto_offerspb_offer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_offerspb_offer_proto_rawDesc), len(file_proto_offerspb_offer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_offerspb_offer_proto_goTypes,
		DependencyIndexes: file_proto_offerspb_offer_proto_depIdxs,
		MessageInfos:      file_proto_offerspb_offer_proto_msgTypes,
	}.Build()
	File_proto_offerspb_offer_proto = out.File
	file_proto_offerspb_offer_proto_goTypes = nil
	file_proto_offerspb_offer_proto_depIdxs = nil
}
