// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: tripspb/trip.proto

package tripspb

import (
	common "github.com/Binit-Dhakal/Saarathi/pkg/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TripRequested struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SagaId        string                 `protobuf:"bytes,1,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	TripId        string                 `protobuf:"bytes,2,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	Distance      float64                `protobuf:"fixed64,3,opt,name=distance,proto3" json:"distance,omitempty"`
	Price         int32                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	PickUp        *common.Coordinates    `protobuf:"bytes,5,opt,name=pick_up,json=pickUp,proto3" json:"pick_up,omitempty"`
	DropOff       *common.Coordinates    `protobuf:"bytes,6,opt,name=drop_off,json=dropOff,proto3" json:"drop_off,omitempty"`
	CarType       string                 `protobuf:"bytes,7,opt,name=car_type,json=carType,proto3" json:"car_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TripRequested) Reset() {
	*x = TripRequested{}
	mi := &file_tripspb_trip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripRequested) ProtoMessage() {}

func (x *TripRequested) ProtoReflect() protoreflect.Message {
	mi := &file_tripspb_trip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripRequested.ProtoReflect.Descriptor instead.
func (*TripRequested) Descriptor() ([]byte, []int) {
	return file_tripspb_trip_proto_rawDescGZIP(), []int{0}
}

func (x *TripRequested) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

func (x *TripRequested) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *TripRequested) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *TripRequested) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TripRequested) GetPickUp() *common.Coordinates {
	if x != nil {
		return x.PickUp
	}
	return nil
}

func (x *TripRequested) GetDropOff() *common.Coordinates {
	if x != nil {
		return x.DropOff
	}
	return nil
}

func (x *TripRequested) GetCarType() string {
	if x != nil {
		return x.CarType
	}
	return ""
}

type TripAssigned struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SagaId        string                 `protobuf:"bytes,1,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	TripId        string                 `protobuf:"bytes,2,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	RiderId       string                 `protobuf:"bytes,4,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TripAssigned) Reset() {
	*x = TripAssigned{}
	mi := &file_tripspb_trip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripAssigned) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripAssigned) ProtoMessage() {}

func (x *TripAssigned) ProtoReflect() protoreflect.Message {
	mi := &file_tripspb_trip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripAssigned.ProtoReflect.Descriptor instead.
func (*TripAssigned) Descriptor() ([]byte, []int) {
	return file_tripspb_trip_proto_rawDescGZIP(), []int{1}
}

func (x *TripAssigned) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

func (x *TripAssigned) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *TripAssigned) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *TripAssigned) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

type RejectTrip struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectTrip) Reset() {
	*x = RejectTrip{}
	mi := &file_tripspb_trip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectTrip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectTrip) ProtoMessage() {}

func (x *RejectTrip) ProtoReflect() protoreflect.Message {
	mi := &file_tripspb_trip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectTrip.ProtoReflect.Descriptor instead.
func (*RejectTrip) Descriptor() ([]byte, []int) {
	return file_tripspb_trip_proto_rawDescGZIP(), []int{2}
}

func (x *RejectTrip) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

var File_tripspb_trip_proto protoreflect.FileDescriptor

const file_tripspb_trip_proto_rawDesc = "" +
	"\n" +
	"\x12tripspb/trip.proto\x12\btrips.v1\x1a\x10common/geo.proto\"\xfa\x01\n" +
	"\rTripRequested\x12\x17\n" +
	"\asaga_id\x18\x01 \x01(\tR\x06sagaId\x12\x17\n" +
	"\atrip_id\x18\x02 \x01(\tR\x06tripId\x12\x1a\n" +
	"\bdistance\x18\x03 \x01(\x01R\bdistance\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x05R\x05price\x123\n" +
	"\apick_up\x18\x05 \x01(\v2\x1a.common.geo.v1.CoordinatesR\x06pickUp\x125\n" +
	"\bdrop_off\x18\x06 \x01(\v2\x1a.common.geo.v1.CoordinatesR\adropOff\x12\x19\n" +
	"\bcar_type\x18\a \x01(\tR\acarType\"x\n" +
	"\fTripAssigned\x12\x17\n" +
	"\asaga_id\x18\x01 \x01(\tR\x06sagaId\x12\x17\n" +
	"\atrip_id\x18\x02 \x01(\tR\x06tripId\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\tR\bdriverId\x12\x19\n" +
	"\brider_id\x18\x04 \x01(\tR\ariderId\"%\n" +
	"\n" +
	"RejectTrip\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripIdB4Z2github.com/Binit-Dhakal/Saarathi/pkg/proto/tripspbb\x06proto3"

var (
	file_tripspb_trip_proto_rawDescOnce sync.Once
	file_tripspb_trip_proto_rawDescData []byte
)

func file_tripspb_trip_proto_rawDescGZIP() []byte {
	file_tripspb_trip_proto_rawDescOnce.Do(func() {
		file_tripspb_trip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tripspb_trip_proto_rawDesc), len(file_tripspb_trip_proto_rawDesc)))
	})
	return file_tripspb_trip_proto_rawDescData
}

var file_tripspb_trip_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tripspb_trip_proto_goTypes = []any{
	(*TripRequested)(nil),      // 0: trips.v1.TripRequested
	(*TripAssigned)(nil),       // 1: trips.v1.TripAssigned
	(*RejectTrip)(nil),         // 2: trips.v1.RejectTrip
	(*common.Coordinates)(nil), // 3: common.geo.v1.Coordinates
}
var file_tripspb_trip_proto_depIdxs = []int32{
	3, // 0: trips.v1.TripRequested.pick_up:type_name -> common.geo.v1.Coordinates
	3, // 1: trips.v1.TripRequested.drop_off:type_name -> common.geo.v1.Coordinates
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tripspb_trip_proto_init() }
func file_tripspb_trip_proto_init() {
	if File_tripspb_trip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tripspb_trip_proto_rawDesc), len(file_tripspb_trip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tripspb_trip_proto_goTypes,
		DependencyIndexes: file_tripspb_trip_proto_depIdxs,
		MessageInfos:      file_tripspb_trip_proto_msgTypes,
	}.Build()
	File_tripspb_trip_proto = out.File
	file_tripspb_trip_proto_goTypes = nil
	file_tripspb_trip_proto_depIdxs = nil
}
