// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/driverspb/driver_state.proto

package driverspb

import (
	_ "github.com/Binit-Dhakal/Saarathi/pkg/contracts/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OfferAccepted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	TripId        string                 `protobuf:"bytes,2,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	SagaId        string                 `protobuf:"bytes,3,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfferAccepted) Reset() {
	*x = OfferAccepted{}
	mi := &file_proto_driverspb_driver_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfferAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferAccepted) ProtoMessage() {}

func (x *OfferAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driverspb_driver_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferAccepted.ProtoReflect.Descriptor instead.
func (*OfferAccepted) Descriptor() ([]byte, []int) {
	return file_proto_driverspb_driver_state_proto_rawDescGZIP(), []int{0}
}

func (x *OfferAccepted) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *OfferAccepted) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *OfferAccepted) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

type OfferRejected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	TripId        string                 `protobuf:"bytes,2,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	SagaId        string                 `protobuf:"bytes,3,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfferRejected) Reset() {
	*x = OfferRejected{}
	mi := &file_proto_driverspb_driver_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfferRejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferRejected) ProtoMessage() {}

func (x *OfferRejected) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driverspb_driver_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferRejected.ProtoReflect.Descriptor instead.
func (*OfferRejected) Descriptor() ([]byte, []int) {
	return file_proto_driverspb_driver_state_proto_rawDescGZIP(), []int{1}
}

func (x *OfferRejected) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *OfferRejected) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *OfferRejected) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

type OfferTimedOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	TripId        string                 `protobuf:"bytes,2,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	SagaId        string                 `protobuf:"bytes,3,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfferTimedOut) Reset() {
	*x = OfferTimedOut{}
	mi := &file_proto_driverspb_driver_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfferTimedOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferTimedOut) ProtoMessage() {}

func (x *OfferTimedOut) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driverspb_driver_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferTimedOut.ProtoReflect.Descriptor instead.
func (*OfferTimedOut) Descriptor() ([]byte, []int) {
	return file_proto_driverspb_driver_state_proto_rawDescGZIP(), []int{2}
}

func (x *OfferTimedOut) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *OfferTimedOut) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *OfferTimedOut) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

var File_proto_driverspb_driver_state_proto protoreflect.FileDescriptor

const file_proto_driverspb_driver_state_proto_rawDesc = "" +
	"\n" +
	"\"proto/driverspb/driver_state.proto\x12\x0fdriversstate.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16proto/common/geo.proto\"^\n" +
	"\rOfferAccepted\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x17\n" +
	"\atrip_id\x18\x02 \x01(\tR\x06tripId\x12\x17\n" +
	"\asaga_id\x18\x03 \x01(\tR\x06sagaId\"^\n" +
	"\rOfferRejected\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x17\n" +
	"\atrip_id\x18\x02 \x01(\tR\x06tripId\x12\x17\n" +
	"\asaga_id\x18\x03 \x01(\tR\x06sagaId\"^\n" +
	"\rOfferTimedOut\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x17\n" +
	"\atrip_id\x18\x02 \x01(\tR\x06tripId\x12\x17\n" +
	"\asaga_id\x18\x03 \x01(\tR\x06sagaIdB@Z>github.com/Binit-Dhakal/Saarathi/pkg/contracts/proto/driverspbb\x06proto3"

var (
	file_proto_driverspb_driver_state_proto_rawDescOnce sync.Once
	file_proto_driverspb_driver_state_proto_rawDescData []byte
)

func file_proto_driverspb_driver_state_proto_rawDescGZIP() []byte {
	file_proto_driverspb_driver_state_proto_rawDescOnce.Do(func() {
		file_proto_driverspb_driver_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_driverspb_driver_state_proto_rawDesc), len(file_proto_driverspb_driver_state_proto_rawDesc)))
	})
	return file_proto_driverspb_driver_state_proto_rawDescData
}

var file_proto_driverspb_driver_state_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_driverspb_driver_state_proto_goTypes = []any{
	(*OfferAccepted)(nil), // 0: driversstate.v1.OfferAccepted
	(*OfferRejected)(nil), // 1: driversstate.v1.OfferRejected
	(*OfferTimedOut)(nil), // 2: driversstate.v1.OfferTimedOut
}
var file_proto_driverspb_driver_state_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_driverspb_driver_state_proto_init() }
func file_proto_driverspb_driver_state_proto_init() {
	if File_proto_driverspb_driver_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_driverspb_driver_state_proto_rawDesc), len(file_proto_driverspb_driver_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_driverspb_driver_state_proto_goTypes,
		DependencyIndexes: file_proto_driverspb_driver_state_proto_depIdxs,
		MessageInfos:      file_proto_driverspb_driver_state_proto_msgTypes,
	}.Build()
	File_proto_driverspb_driver_state_proto = out.File
	file_proto_driverspb_driver_state_proto_goTypes = nil
	file_proto_driverspb_driver_state_proto_depIdxs = nil
}
