apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - osrm-pv-pvc.yaml
  - ../../base/osrm
  - ../../base/trips
  - ../../base/users
  - ../../base/api-gateway

patches:
  - path: osrm-deployment-patch.yaml
    target:
      kind: Deployment
      name: osrm-backend

