apiVersion: v1
kind: PersistentVolume
metadata:
  name: osrm-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /data/osrm

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: osrm-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi


