// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: message_type.proto

package am

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventMessageData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	OccuredAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=occured_at,json=occuredAt,proto3" json:"occured_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventMessageData) Reset() {
	*x = EventMessageData{}
	mi := &file_message_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMessageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMessageData) ProtoMessage() {}

func (x *EventMessageData) ProtoReflect() protoreflect.Message {
	mi := &file_message_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMessageData.ProtoReflect.Descriptor instead.
func (*EventMessageData) Descriptor() ([]byte, []int) {
	return file_message_type_proto_rawDescGZIP(), []int{0}
}

func (x *EventMessageData) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EventMessageData) GetOccuredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccuredAt
	}
	return nil
}

var File_message_type_proto protoreflect.FileDescriptor

const file_message_type_proto_rawDesc = "" +
	"\n" +
	"\x12message_type.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"g\n" +
	"\x10EventMessageData\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x129\n" +
	"\n" +
	"occured_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\toccuredAtB=B\x10MessageTypeProtoP\x01Z'github.com/Binit-Dhakal/Saarathi/pkg/amb\x06proto3"

var (
	file_message_type_proto_rawDescOnce sync.Once
	file_message_type_proto_rawDescData []byte
)

func file_message_type_proto_rawDescGZIP() []byte {
	file_message_type_proto_rawDescOnce.Do(func() {
		file_message_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_type_proto_rawDesc), len(file_message_type_proto_rawDesc)))
	})
	return file_message_type_proto_rawDescData
}

var file_message_type_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_type_proto_goTypes = []any{
	(*EventMessageData)(nil),      // 0: EventMessageData
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_message_type_proto_depIdxs = []int32{
	1, // 0: EventMessageData.occured_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_message_type_proto_init() }
func file_message_type_proto_init() {
	if File_message_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_type_proto_rawDesc), len(file_message_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_type_proto_goTypes,
		DependencyIndexes: file_message_type_proto_depIdxs,
		MessageInfos:      file_message_type_proto_msgTypes,
	}.Build()
	File_message_type_proto = out.File
	file_message_type_proto_goTypes = nil
	file_message_type_proto_depIdxs = nil
}
